### ISSUE TITLE
Upgrade paramiko from 2.4.2 to remove deprecation warning

### ISSUE THREAD

**Issue by sverch** [getcloudless/cloudless#86]
**Describe the bug**

I get these errors running tests: https://github.com/paramiko/paramiko/issues/1386

**To reproduce**

Run tests on latest master.

**Expected behavior**

Tests pass with no warnings.

**Platform info**

- Version of Cloudless: Currently running on https://github.com/getcloudless/cloudless/pull/85 branch, but that will be merged soon.

**Comment by cowlinator** [comment]
FYI, paramiko has released 2.5.0, which no longer uses deprecated cryptography calls.
https://github.com/paramiko/paramiko/releases/tag/2.5.0

**Comment by sverch** [comment]
Awesome, thanks for the update @cowlinator!
